### ISSUE TITLE
unnecessary scrollbar, sendbox partially blocked

### ISSUE THREAD

**Issue by liyuankui** [rhinobird-io/rhinobird-web#107]
![image](https://cloud.githubusercontent.com/assets/869483/7805259/a4efcac4-03a1-11e5-9edd-a9615ef5367b.png)

``` css
.send-box {
  background-color: #fff;
  margin: 1em;
  flex: 0 0 auto;
}
```
